// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class XfutebolBridge
    extends
        BaseEntrypoint<
          XfutebolBridgeApi,
          XfutebolBridgeApiImpl,
          XfutebolBridgeWire
        > {
  @internal
  static final instance = XfutebolBridge._();

  XfutebolBridge._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    XfutebolBridgeApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required XfutebolBridgeApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<XfutebolBridgeApiImpl, XfutebolBridgeWire>
  get apiImplConstructor => XfutebolBridgeApiImpl.new;

  @override
  WireConstructor<XfutebolBridgeWire> get wireConstructor =>
      XfutebolBridgeWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -1553868706;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'xfutebol_flutter_bridge',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class XfutebolBridgeApi extends BaseApi {
  Future<bool> crateApiDeleteGame({required String gameId});

  Future<ActionResult> crateApiExecuteDefend({
    required String gameId,
    required String pieceId,
    required List<Position> path,
  });

  Future<ActionResult> crateApiExecuteIntercept({
    required String gameId,
    required String pieceId,
    required List<Position> path,
  });

  Future<ActionResult> crateApiExecuteKick({
    required String gameId,
    required String pieceId,
    required List<Position> path,
  });

  Future<ActionResult> crateApiExecuteMove({
    required String gameId,
    required String pieceId,
    required Position to,
  });

  Future<ActionResult> crateApiExecutePass({
    required String gameId,
    required String pieceId,
    required List<Position> path,
  });

  Future<ActionResult> crateApiExecutePush({
    required String gameId,
    required String pieceId,
    required Position target,
    required Position destination,
  });

  Future<ActionResult> crateApiExecuteShoot({
    required String gameId,
    required String pieceId,
    required List<Position> path,
  });

  Future<bool> crateApiGameExists({required String gameId});

  Future<BoardView?> crateApiGetBoard({required String gameId});

  Future<BotAction?> crateApiGetBotAction({
    required String gameId,
    required Difficulty difficulty,
  });

  Future<(String, Position)?> crateApiGetBotMove({
    required String gameId,
    required Difficulty difficulty,
  });

  Future<List<PositionPath>> crateApiGetLegalDefends({
    required String gameId,
    required String pieceId,
  });

  Future<List<PositionPath>> crateApiGetLegalIntercepts({
    required String gameId,
    required String pieceId,
  });

  Future<List<PositionPath>> crateApiGetLegalKicks({
    required String gameId,
    required String pieceId,
  });

  Future<List<Position>> crateApiGetLegalMoves({
    required String gameId,
    required String pieceId,
  });

  Future<List<PositionPath>> crateApiGetLegalPasses({
    required String gameId,
    required String pieceId,
  });

  Future<List<PositionPath>> crateApiGetLegalPushes({
    required String gameId,
    required String pieceId,
  });

  Future<List<PositionPath>> crateApiGetLegalShoots({
    required String gameId,
    required String pieceId,
  });

  Future<Team?> crateApiGetWinner({required String gameId});

  Future<String> crateApiGreet({required String name});

  Future<bool> crateApiIsGameOver({required String gameId});

  Future<String> crateApiNewGame({required GameModeType mode});
}

class XfutebolBridgeApiImpl extends XfutebolBridgeApiImplPlatform
    implements XfutebolBridgeApi {
  XfutebolBridgeApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<bool> crateApiDeleteGame({required String gameId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(gameId);
          return wire.wire__crate__api__delete_game(port_, arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDeleteGameConstMeta,
        argValues: [gameId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDeleteGameConstMeta =>
      const TaskConstMeta(debugName: "delete_game", argNames: ["gameId"]);

  @override
  Future<ActionResult> crateApiExecuteDefend({
    required String gameId,
    required String pieceId,
    required List<Position> path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(gameId);
          var arg1 = cst_encode_String(pieceId);
          var arg2 = cst_encode_list_position(path);
          return wire.wire__crate__api__execute_defend(port_, arg0, arg1, arg2);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_action_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiExecuteDefendConstMeta,
        argValues: [gameId, pieceId, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiExecuteDefendConstMeta => const TaskConstMeta(
    debugName: "execute_defend",
    argNames: ["gameId", "pieceId", "path"],
  );

  @override
  Future<ActionResult> crateApiExecuteIntercept({
    required String gameId,
    required String pieceId,
    required List<Position> path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(gameId);
          var arg1 = cst_encode_String(pieceId);
          var arg2 = cst_encode_list_position(path);
          return wire.wire__crate__api__execute_intercept(
            port_,
            arg0,
            arg1,
            arg2,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_action_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiExecuteInterceptConstMeta,
        argValues: [gameId, pieceId, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiExecuteInterceptConstMeta => const TaskConstMeta(
    debugName: "execute_intercept",
    argNames: ["gameId", "pieceId", "path"],
  );

  @override
  Future<ActionResult> crateApiExecuteKick({
    required String gameId,
    required String pieceId,
    required List<Position> path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(gameId);
          var arg1 = cst_encode_String(pieceId);
          var arg2 = cst_encode_list_position(path);
          return wire.wire__crate__api__execute_kick(port_, arg0, arg1, arg2);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_action_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiExecuteKickConstMeta,
        argValues: [gameId, pieceId, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiExecuteKickConstMeta => const TaskConstMeta(
    debugName: "execute_kick",
    argNames: ["gameId", "pieceId", "path"],
  );

  @override
  Future<ActionResult> crateApiExecuteMove({
    required String gameId,
    required String pieceId,
    required Position to,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(gameId);
          var arg1 = cst_encode_String(pieceId);
          var arg2 = cst_encode_box_autoadd_position(to);
          return wire.wire__crate__api__execute_move(port_, arg0, arg1, arg2);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_action_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiExecuteMoveConstMeta,
        argValues: [gameId, pieceId, to],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiExecuteMoveConstMeta => const TaskConstMeta(
    debugName: "execute_move",
    argNames: ["gameId", "pieceId", "to"],
  );

  @override
  Future<ActionResult> crateApiExecutePass({
    required String gameId,
    required String pieceId,
    required List<Position> path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(gameId);
          var arg1 = cst_encode_String(pieceId);
          var arg2 = cst_encode_list_position(path);
          return wire.wire__crate__api__execute_pass(port_, arg0, arg1, arg2);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_action_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiExecutePassConstMeta,
        argValues: [gameId, pieceId, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiExecutePassConstMeta => const TaskConstMeta(
    debugName: "execute_pass",
    argNames: ["gameId", "pieceId", "path"],
  );

  @override
  Future<ActionResult> crateApiExecutePush({
    required String gameId,
    required String pieceId,
    required Position target,
    required Position destination,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(gameId);
          var arg1 = cst_encode_String(pieceId);
          var arg2 = cst_encode_box_autoadd_position(target);
          var arg3 = cst_encode_box_autoadd_position(destination);
          return wire.wire__crate__api__execute_push(
            port_,
            arg0,
            arg1,
            arg2,
            arg3,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_action_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiExecutePushConstMeta,
        argValues: [gameId, pieceId, target, destination],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiExecutePushConstMeta => const TaskConstMeta(
    debugName: "execute_push",
    argNames: ["gameId", "pieceId", "target", "destination"],
  );

  @override
  Future<ActionResult> crateApiExecuteShoot({
    required String gameId,
    required String pieceId,
    required List<Position> path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(gameId);
          var arg1 = cst_encode_String(pieceId);
          var arg2 = cst_encode_list_position(path);
          return wire.wire__crate__api__execute_shoot(port_, arg0, arg1, arg2);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_action_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiExecuteShootConstMeta,
        argValues: [gameId, pieceId, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiExecuteShootConstMeta => const TaskConstMeta(
    debugName: "execute_shoot",
    argNames: ["gameId", "pieceId", "path"],
  );

  @override
  Future<bool> crateApiGameExists({required String gameId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(gameId);
          return wire.wire__crate__api__game_exists(port_, arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGameExistsConstMeta,
        argValues: [gameId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGameExistsConstMeta =>
      const TaskConstMeta(debugName: "game_exists", argNames: ["gameId"]);

  @override
  Future<BoardView?> crateApiGetBoard({required String gameId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(gameId);
          return wire.wire__crate__api__get_board(port_, arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_opt_box_autoadd_board_view,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGetBoardConstMeta,
        argValues: [gameId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetBoardConstMeta =>
      const TaskConstMeta(debugName: "get_board", argNames: ["gameId"]);

  @override
  Future<BotAction?> crateApiGetBotAction({
    required String gameId,
    required Difficulty difficulty,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(gameId);
          var arg1 = cst_encode_difficulty(difficulty);
          return wire.wire__crate__api__get_bot_action(port_, arg0, arg1);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_opt_box_autoadd_bot_action,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGetBotActionConstMeta,
        argValues: [gameId, difficulty],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetBotActionConstMeta => const TaskConstMeta(
    debugName: "get_bot_action",
    argNames: ["gameId", "difficulty"],
  );

  @override
  Future<(String, Position)?> crateApiGetBotMove({
    required String gameId,
    required Difficulty difficulty,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(gameId);
          var arg1 = cst_encode_difficulty(difficulty);
          return wire.wire__crate__api__get_bot_move(port_, arg0, arg1);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_opt_box_autoadd_record_string_position,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGetBotMoveConstMeta,
        argValues: [gameId, difficulty],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetBotMoveConstMeta => const TaskConstMeta(
    debugName: "get_bot_move",
    argNames: ["gameId", "difficulty"],
  );

  @override
  Future<List<PositionPath>> crateApiGetLegalDefends({
    required String gameId,
    required String pieceId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(gameId);
          var arg1 = cst_encode_String(pieceId);
          return wire.wire__crate__api__get_legal_defends(port_, arg0, arg1);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_list_position_path,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGetLegalDefendsConstMeta,
        argValues: [gameId, pieceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetLegalDefendsConstMeta => const TaskConstMeta(
    debugName: "get_legal_defends",
    argNames: ["gameId", "pieceId"],
  );

  @override
  Future<List<PositionPath>> crateApiGetLegalIntercepts({
    required String gameId,
    required String pieceId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(gameId);
          var arg1 = cst_encode_String(pieceId);
          return wire.wire__crate__api__get_legal_intercepts(port_, arg0, arg1);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_list_position_path,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGetLegalInterceptsConstMeta,
        argValues: [gameId, pieceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetLegalInterceptsConstMeta => const TaskConstMeta(
    debugName: "get_legal_intercepts",
    argNames: ["gameId", "pieceId"],
  );

  @override
  Future<List<PositionPath>> crateApiGetLegalKicks({
    required String gameId,
    required String pieceId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(gameId);
          var arg1 = cst_encode_String(pieceId);
          return wire.wire__crate__api__get_legal_kicks(port_, arg0, arg1);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_list_position_path,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGetLegalKicksConstMeta,
        argValues: [gameId, pieceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetLegalKicksConstMeta => const TaskConstMeta(
    debugName: "get_legal_kicks",
    argNames: ["gameId", "pieceId"],
  );

  @override
  Future<List<Position>> crateApiGetLegalMoves({
    required String gameId,
    required String pieceId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(gameId);
          var arg1 = cst_encode_String(pieceId);
          return wire.wire__crate__api__get_legal_moves(port_, arg0, arg1);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_list_position,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGetLegalMovesConstMeta,
        argValues: [gameId, pieceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetLegalMovesConstMeta => const TaskConstMeta(
    debugName: "get_legal_moves",
    argNames: ["gameId", "pieceId"],
  );

  @override
  Future<List<PositionPath>> crateApiGetLegalPasses({
    required String gameId,
    required String pieceId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(gameId);
          var arg1 = cst_encode_String(pieceId);
          return wire.wire__crate__api__get_legal_passes(port_, arg0, arg1);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_list_position_path,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGetLegalPassesConstMeta,
        argValues: [gameId, pieceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetLegalPassesConstMeta => const TaskConstMeta(
    debugName: "get_legal_passes",
    argNames: ["gameId", "pieceId"],
  );

  @override
  Future<List<PositionPath>> crateApiGetLegalPushes({
    required String gameId,
    required String pieceId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(gameId);
          var arg1 = cst_encode_String(pieceId);
          return wire.wire__crate__api__get_legal_pushes(port_, arg0, arg1);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_list_position_path,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGetLegalPushesConstMeta,
        argValues: [gameId, pieceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetLegalPushesConstMeta => const TaskConstMeta(
    debugName: "get_legal_pushes",
    argNames: ["gameId", "pieceId"],
  );

  @override
  Future<List<PositionPath>> crateApiGetLegalShoots({
    required String gameId,
    required String pieceId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(gameId);
          var arg1 = cst_encode_String(pieceId);
          return wire.wire__crate__api__get_legal_shoots(port_, arg0, arg1);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_list_position_path,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGetLegalShootsConstMeta,
        argValues: [gameId, pieceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetLegalShootsConstMeta => const TaskConstMeta(
    debugName: "get_legal_shoots",
    argNames: ["gameId", "pieceId"],
  );

  @override
  Future<Team?> crateApiGetWinner({required String gameId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(gameId);
          return wire.wire__crate__api__get_winner(port_, arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_opt_box_autoadd_team,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGetWinnerConstMeta,
        argValues: [gameId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetWinnerConstMeta =>
      const TaskConstMeta(debugName: "get_winner", argNames: ["gameId"]);

  @override
  Future<String> crateApiGreet({required String name}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(name);
          return wire.wire__crate__api__greet(port_, arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<bool> crateApiIsGameOver({required String gameId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(gameId);
          return wire.wire__crate__api__is_game_over(port_, arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiIsGameOverConstMeta,
        argValues: [gameId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIsGameOverConstMeta =>
      const TaskConstMeta(debugName: "is_game_over", argNames: ["gameId"]);

  @override
  Future<String> crateApiNewGame({required GameModeType mode}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_game_mode_type(mode);
          return wire.wire__crate__api__new_game(port_, arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNewGameConstMeta,
        argValues: [mode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNewGameConstMeta =>
      const TaskConstMeta(debugName: "new_game", argNames: ["mode"]);

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  ActionResult dco_decode_action_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return ActionResult(
      success: dco_decode_bool(arr[0]),
      message: dco_decode_String(arr[1]),
      gameOver: dco_decode_bool(arr[2]),
      winner: dco_decode_opt_box_autoadd_team(arr[3]),
      actionsRemaining: dco_decode_u_8(arr[4]),
      goalScored: dco_decode_opt_box_autoadd_team(arr[5]),
      turnEnded: dco_decode_bool(arr[6]),
      kickoffReset: dco_decode_bool(arr[7]),
    );
  }

  @protected
  ActionType dco_decode_action_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ActionType.values[raw as int];
  }

  @protected
  BoardView dco_decode_board_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return BoardView(
      pieces: dco_decode_list_piece_view(arr[0]),
      ballPosition: dco_decode_opt_box_autoadd_position(arr[1]),
      currentTurn: dco_decode_team(arr[2]),
      actionsRemaining: dco_decode_u_8(arr[3]),
      whiteScore: dco_decode_u_8(arr[4]),
      blackScore: dco_decode_u_8(arr[5]),
      turnNumber: dco_decode_u_32(arr[6]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  BotAction dco_decode_bot_action(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return BotAction(
      pieceId: dco_decode_String(arr[0]),
      actionType: dco_decode_action_type(arr[1]),
      path: dco_decode_list_position(arr[2]),
    );
  }

  @protected
  BoardView dco_decode_box_autoadd_board_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_board_view(raw);
  }

  @protected
  BotAction dco_decode_box_autoadd_bot_action(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_bot_action(raw);
  }

  @protected
  Position dco_decode_box_autoadd_position(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_position(raw);
  }

  @protected
  (String, Position) dco_decode_box_autoadd_record_string_position(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as (String, Position);
  }

  @protected
  Team dco_decode_box_autoadd_team(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_team(raw);
  }

  @protected
  Difficulty dco_decode_difficulty(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Difficulty.values[raw as int];
  }

  @protected
  GameModeType dco_decode_game_mode_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return GameModeType.values[raw as int];
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<PieceView> dco_decode_list_piece_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_piece_view).toList();
  }

  @protected
  List<Position> dco_decode_list_position(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_position).toList();
  }

  @protected
  List<PositionPath> dco_decode_list_position_path(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_position_path).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  BoardView? dco_decode_opt_box_autoadd_board_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_board_view(raw);
  }

  @protected
  BotAction? dco_decode_opt_box_autoadd_bot_action(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_bot_action(raw);
  }

  @protected
  Position? dco_decode_opt_box_autoadd_position(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_position(raw);
  }

  @protected
  (String, Position)? dco_decode_opt_box_autoadd_record_string_position(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_record_string_position(raw);
  }

  @protected
  Team? dco_decode_opt_box_autoadd_team(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_team(raw);
  }

  @protected
  PieceRole dco_decode_piece_role(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PieceRole.values[raw as int];
  }

  @protected
  PieceView dco_decode_piece_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return PieceView(
      id: dco_decode_String(arr[0]),
      team: dco_decode_team(arr[1]),
      role: dco_decode_piece_role(arr[2]),
      position: dco_decode_position(arr[3]),
      hasBall: dco_decode_bool(arr[4]),
    );
  }

  @protected
  Position dco_decode_position(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return Position(row: dco_decode_u_8(arr[0]), col: dco_decode_u_8(arr[1]));
  }

  @protected
  PositionPath dco_decode_position_path(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return PositionPath(positions: dco_decode_list_position(arr[0]));
  }

  @protected
  (String, Position) dco_decode_record_string_position(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_String(arr[0]), dco_decode_position(arr[1]));
  }

  @protected
  Team dco_decode_team(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Team.values[raw as int];
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  ActionResult sse_decode_action_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_success = sse_decode_bool(deserializer);
    var var_message = sse_decode_String(deserializer);
    var var_gameOver = sse_decode_bool(deserializer);
    var var_winner = sse_decode_opt_box_autoadd_team(deserializer);
    var var_actionsRemaining = sse_decode_u_8(deserializer);
    var var_goalScored = sse_decode_opt_box_autoadd_team(deserializer);
    var var_turnEnded = sse_decode_bool(deserializer);
    var var_kickoffReset = sse_decode_bool(deserializer);
    return ActionResult(
      success: var_success,
      message: var_message,
      gameOver: var_gameOver,
      winner: var_winner,
      actionsRemaining: var_actionsRemaining,
      goalScored: var_goalScored,
      turnEnded: var_turnEnded,
      kickoffReset: var_kickoffReset,
    );
  }

  @protected
  ActionType sse_decode_action_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ActionType.values[inner];
  }

  @protected
  BoardView sse_decode_board_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_pieces = sse_decode_list_piece_view(deserializer);
    var var_ballPosition = sse_decode_opt_box_autoadd_position(deserializer);
    var var_currentTurn = sse_decode_team(deserializer);
    var var_actionsRemaining = sse_decode_u_8(deserializer);
    var var_whiteScore = sse_decode_u_8(deserializer);
    var var_blackScore = sse_decode_u_8(deserializer);
    var var_turnNumber = sse_decode_u_32(deserializer);
    return BoardView(
      pieces: var_pieces,
      ballPosition: var_ballPosition,
      currentTurn: var_currentTurn,
      actionsRemaining: var_actionsRemaining,
      whiteScore: var_whiteScore,
      blackScore: var_blackScore,
      turnNumber: var_turnNumber,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  BotAction sse_decode_bot_action(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_pieceId = sse_decode_String(deserializer);
    var var_actionType = sse_decode_action_type(deserializer);
    var var_path = sse_decode_list_position(deserializer);
    return BotAction(
      pieceId: var_pieceId,
      actionType: var_actionType,
      path: var_path,
    );
  }

  @protected
  BoardView sse_decode_box_autoadd_board_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_board_view(deserializer));
  }

  @protected
  BotAction sse_decode_box_autoadd_bot_action(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_bot_action(deserializer));
  }

  @protected
  Position sse_decode_box_autoadd_position(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_position(deserializer));
  }

  @protected
  (String, Position) sse_decode_box_autoadd_record_string_position(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_record_string_position(deserializer));
  }

  @protected
  Team sse_decode_box_autoadd_team(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_team(deserializer));
  }

  @protected
  Difficulty sse_decode_difficulty(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return Difficulty.values[inner];
  }

  @protected
  GameModeType sse_decode_game_mode_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return GameModeType.values[inner];
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<PieceView> sse_decode_list_piece_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PieceView>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_piece_view(deserializer));
    }
    return ans_;
  }

  @protected
  List<Position> sse_decode_list_position(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Position>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_position(deserializer));
    }
    return ans_;
  }

  @protected
  List<PositionPath> sse_decode_list_position_path(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PositionPath>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_position_path(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  BoardView? sse_decode_opt_box_autoadd_board_view(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_board_view(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BotAction? sse_decode_opt_box_autoadd_bot_action(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_bot_action(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Position? sse_decode_opt_box_autoadd_position(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_position(deserializer));
    } else {
      return null;
    }
  }

  @protected
  (String, Position)? sse_decode_opt_box_autoadd_record_string_position(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_record_string_position(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Team? sse_decode_opt_box_autoadd_team(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_team(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PieceRole sse_decode_piece_role(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return PieceRole.values[inner];
  }

  @protected
  PieceView sse_decode_piece_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_team = sse_decode_team(deserializer);
    var var_role = sse_decode_piece_role(deserializer);
    var var_position = sse_decode_position(deserializer);
    var var_hasBall = sse_decode_bool(deserializer);
    return PieceView(
      id: var_id,
      team: var_team,
      role: var_role,
      position: var_position,
      hasBall: var_hasBall,
    );
  }

  @protected
  Position sse_decode_position(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_row = sse_decode_u_8(deserializer);
    var var_col = sse_decode_u_8(deserializer);
    return Position(row: var_row, col: var_col);
  }

  @protected
  PositionPath sse_decode_position_path(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_positions = sse_decode_list_position(deserializer);
    return PositionPath(positions: var_positions);
  }

  @protected
  (String, Position) sse_decode_record_string_position(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_position(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  Team sse_decode_team(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return Team.values[inner];
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int cst_encode_action_type(ActionType raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_i_32(raw.index);
  }

  @protected
  bool cst_encode_bool(bool raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_difficulty(Difficulty raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_i_32(raw.index);
  }

  @protected
  int cst_encode_game_mode_type(GameModeType raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_i_32(raw.index);
  }

  @protected
  int cst_encode_i_32(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_piece_role(PieceRole raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_i_32(raw.index);
  }

  @protected
  int cst_encode_team(Team raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_i_32(raw.index);
  }

  @protected
  int cst_encode_u_32(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_u_8(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  void cst_encode_unit(void raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_action_result(ActionResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.success, serializer);
    sse_encode_String(self.message, serializer);
    sse_encode_bool(self.gameOver, serializer);
    sse_encode_opt_box_autoadd_team(self.winner, serializer);
    sse_encode_u_8(self.actionsRemaining, serializer);
    sse_encode_opt_box_autoadd_team(self.goalScored, serializer);
    sse_encode_bool(self.turnEnded, serializer);
    sse_encode_bool(self.kickoffReset, serializer);
  }

  @protected
  void sse_encode_action_type(ActionType self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_board_view(BoardView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_piece_view(self.pieces, serializer);
    sse_encode_opt_box_autoadd_position(self.ballPosition, serializer);
    sse_encode_team(self.currentTurn, serializer);
    sse_encode_u_8(self.actionsRemaining, serializer);
    sse_encode_u_8(self.whiteScore, serializer);
    sse_encode_u_8(self.blackScore, serializer);
    sse_encode_u_32(self.turnNumber, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_bot_action(BotAction self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.pieceId, serializer);
    sse_encode_action_type(self.actionType, serializer);
    sse_encode_list_position(self.path, serializer);
  }

  @protected
  void sse_encode_box_autoadd_board_view(
    BoardView self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_board_view(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_bot_action(
    BotAction self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bot_action(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_position(
    Position self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_position(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_record_string_position(
    (String, Position) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_record_string_position(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_team(Team self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_team(self, serializer);
  }

  @protected
  void sse_encode_difficulty(Difficulty self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_game_mode_type(GameModeType self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_piece_view(
    List<PieceView> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_piece_view(item, serializer);
    }
  }

  @protected
  void sse_encode_list_position(List<Position> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_position(item, serializer);
    }
  }

  @protected
  void sse_encode_list_position_path(
    List<PositionPath> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_position_path(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_box_autoadd_board_view(
    BoardView? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_board_view(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_bot_action(
    BotAction? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_bot_action(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_position(
    Position? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_position(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_record_string_position(
    (String, Position)? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_record_string_position(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_team(Team? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_team(self, serializer);
    }
  }

  @protected
  void sse_encode_piece_role(PieceRole self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_piece_view(PieceView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_team(self.team, serializer);
    sse_encode_piece_role(self.role, serializer);
    sse_encode_position(self.position, serializer);
    sse_encode_bool(self.hasBall, serializer);
  }

  @protected
  void sse_encode_position(Position self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_8(self.row, serializer);
    sse_encode_u_8(self.col, serializer);
  }

  @protected
  void sse_encode_position_path(PositionPath self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_position(self.positions, serializer);
  }

  @protected
  void sse_encode_record_string_position(
    (String, Position) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_position(self.$2, serializer);
  }

  @protected
  void sse_encode_team(Team self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
