// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class XfutebolBridgeApiImplPlatform
    extends BaseApiImpl<XfutebolBridgeWire> {
  XfutebolBridgeApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  ActionResult dco_decode_action_result(dynamic raw);

  @protected
  BoardView dco_decode_board_view(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  Position dco_decode_box_autoadd_position(dynamic raw);

  @protected
  (int, Position) dco_decode_box_autoadd_record_u_8_position(dynamic raw);

  @protected
  Team dco_decode_box_autoadd_team(dynamic raw);

  @protected
  Difficulty dco_decode_difficulty(dynamic raw);

  @protected
  GameModeType dco_decode_game_mode_type(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<PieceView> dco_decode_list_piece_view(dynamic raw);

  @protected
  List<Position> dco_decode_list_position(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  Position? dco_decode_opt_box_autoadd_position(dynamic raw);

  @protected
  (int, Position)? dco_decode_opt_box_autoadd_record_u_8_position(dynamic raw);

  @protected
  Team? dco_decode_opt_box_autoadd_team(dynamic raw);

  @protected
  PieceRole dco_decode_piece_role(dynamic raw);

  @protected
  PieceView dco_decode_piece_view(dynamic raw);

  @protected
  Position dco_decode_position(dynamic raw);

  @protected
  (int, Position) dco_decode_record_u_8_position(dynamic raw);

  @protected
  Team dco_decode_team(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  ActionResult sse_decode_action_result(SseDeserializer deserializer);

  @protected
  BoardView sse_decode_board_view(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  Position sse_decode_box_autoadd_position(SseDeserializer deserializer);

  @protected
  (int, Position) sse_decode_box_autoadd_record_u_8_position(
    SseDeserializer deserializer,
  );

  @protected
  Team sse_decode_box_autoadd_team(SseDeserializer deserializer);

  @protected
  Difficulty sse_decode_difficulty(SseDeserializer deserializer);

  @protected
  GameModeType sse_decode_game_mode_type(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<PieceView> sse_decode_list_piece_view(SseDeserializer deserializer);

  @protected
  List<Position> sse_decode_list_position(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  Position? sse_decode_opt_box_autoadd_position(SseDeserializer deserializer);

  @protected
  (int, Position)? sse_decode_opt_box_autoadd_record_u_8_position(
    SseDeserializer deserializer,
  );

  @protected
  Team? sse_decode_opt_box_autoadd_team(SseDeserializer deserializer);

  @protected
  PieceRole sse_decode_piece_role(SseDeserializer deserializer);

  @protected
  PieceView sse_decode_piece_view(SseDeserializer deserializer);

  @protected
  Position sse_decode_position(SseDeserializer deserializer);

  @protected
  (int, Position) sse_decode_record_u_8_position(SseDeserializer deserializer);

  @protected
  Team sse_decode_team(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  String cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  JSAny cst_encode_action_result(ActionResult raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_bool(raw.success),
      cst_encode_String(raw.message),
      cst_encode_bool(raw.gameOver),
      cst_encode_opt_box_autoadd_team(raw.winner),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_board_view(BoardView raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_list_piece_view(raw.pieces),
      cst_encode_opt_box_autoadd_position(raw.ballPosition),
      cst_encode_team(raw.currentTurn),
      cst_encode_u_8(raw.actionsRemaining),
      cst_encode_u_8(raw.whiteScore),
      cst_encode_u_8(raw.blackScore),
      cst_encode_u_32(raw.turnNumber),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_box_autoadd_position(Position raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_position(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_record_u_8_position((int, Position) raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_record_u_8_position(raw);
  }

  @protected
  int cst_encode_box_autoadd_team(Team raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_team(raw);
  }

  @protected
  JSAny cst_encode_list_piece_view(List<PieceView> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_piece_view).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_position(List<Position> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_position).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_prim_u_8_strict(Uint8List raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.jsify()!;
  }

  @protected
  JSAny? cst_encode_opt_box_autoadd_position(Position? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_position(raw);
  }

  @protected
  JSAny? cst_encode_opt_box_autoadd_record_u_8_position((int, Position)? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_record_u_8_position(raw);
  }

  @protected
  int? cst_encode_opt_box_autoadd_team(Team? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_team(raw);
  }

  @protected
  JSAny cst_encode_piece_view(PieceView raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_u_8(raw.id),
      cst_encode_team(raw.team),
      cst_encode_piece_role(raw.role),
      cst_encode_position(raw.position),
      cst_encode_bool(raw.hasBall),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_position(Position raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [cst_encode_u_8(raw.row), cst_encode_u_8(raw.col)].jsify()!;
  }

  @protected
  JSAny cst_encode_record_u_8_position((int, Position) raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [cst_encode_u_8(raw.$1), cst_encode_position(raw.$2)].jsify()!;
  }

  @protected
  bool cst_encode_bool(bool raw);

  @protected
  int cst_encode_difficulty(Difficulty raw);

  @protected
  int cst_encode_game_mode_type(GameModeType raw);

  @protected
  int cst_encode_i_32(int raw);

  @protected
  int cst_encode_piece_role(PieceRole raw);

  @protected
  int cst_encode_team(Team raw);

  @protected
  int cst_encode_u_32(int raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_action_result(ActionResult self, SseSerializer serializer);

  @protected
  void sse_encode_board_view(BoardView self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_position(Position self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_record_u_8_position(
    (int, Position) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_team(Team self, SseSerializer serializer);

  @protected
  void sse_encode_difficulty(Difficulty self, SseSerializer serializer);

  @protected
  void sse_encode_game_mode_type(GameModeType self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_piece_view(
    List<PieceView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_position(List<Position> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_position(
    Position? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_record_u_8_position(
    (int, Position)? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_team(Team? self, SseSerializer serializer);

  @protected
  void sse_encode_piece_role(PieceRole self, SseSerializer serializer);

  @protected
  void sse_encode_piece_view(PieceView self, SseSerializer serializer);

  @protected
  void sse_encode_position(Position self, SseSerializer serializer);

  @protected
  void sse_encode_record_u_8_position(
    (int, Position) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_team(Team self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class XfutebolBridgeWire implements BaseWire {
  XfutebolBridgeWire.fromExternalLibrary(ExternalLibrary lib);

  void wire__crate__api__execute_move(
    NativePortType port_,
    String game_id,
    int piece_id,
    JSAny to,
  ) => wasmModule.wire__crate__api__execute_move(port_, game_id, piece_id, to);

  void wire__crate__api__get_board(NativePortType port_, String game_id) =>
      wasmModule.wire__crate__api__get_board(port_, game_id);

  void wire__crate__api__get_bot_move(
    NativePortType port_,
    String game_id,
    int difficulty,
  ) => wasmModule.wire__crate__api__get_bot_move(port_, game_id, difficulty);

  void wire__crate__api__get_legal_moves(
    NativePortType port_,
    String game_id,
    int piece_id,
  ) => wasmModule.wire__crate__api__get_legal_moves(port_, game_id, piece_id);

  void wire__crate__api__get_winner(NativePortType port_, String game_id) =>
      wasmModule.wire__crate__api__get_winner(port_, game_id);

  void wire__crate__api__greet(NativePortType port_, String name) =>
      wasmModule.wire__crate__api__greet(port_, name);

  void wire__crate__api__is_game_over(NativePortType port_, String game_id) =>
      wasmModule.wire__crate__api__is_game_over(port_, game_id);

  void wire__crate__api__new_game(NativePortType port_, int mode) =>
      wasmModule.wire__crate__api__new_game(port_, mode);
}

@JS('wasm_bindgen')
external XfutebolBridgeWasmModule get wasmModule;

@JS()
@anonymous
extension type XfutebolBridgeWasmModule._(JSObject _) implements JSObject {
  external void wire__crate__api__execute_move(
    NativePortType port_,
    String game_id,
    int piece_id,
    JSAny to,
  );

  external void wire__crate__api__get_board(
    NativePortType port_,
    String game_id,
  );

  external void wire__crate__api__get_bot_move(
    NativePortType port_,
    String game_id,
    int difficulty,
  );

  external void wire__crate__api__get_legal_moves(
    NativePortType port_,
    String game_id,
    int piece_id,
  );

  external void wire__crate__api__get_winner(
    NativePortType port_,
    String game_id,
  );

  external void wire__crate__api__greet(NativePortType port_, String name);

  external void wire__crate__api__is_game_over(
    NativePortType port_,
    String game_id,
  );

  external void wire__crate__api__new_game(NativePortType port_, int mode);
}
