// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class XfutebolBridgeApiImplPlatform
    extends BaseApiImpl<XfutebolBridgeWire> {
  XfutebolBridgeApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  ActionResult dco_decode_action_result(dynamic raw);

  @protected
  ActionType dco_decode_action_type(dynamic raw);

  @protected
  BoardView dco_decode_board_view(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  BotAction dco_decode_bot_action(dynamic raw);

  @protected
  BoardView dco_decode_box_autoadd_board_view(dynamic raw);

  @protected
  BotAction dco_decode_box_autoadd_bot_action(dynamic raw);

  @protected
  Position dco_decode_box_autoadd_position(dynamic raw);

  @protected
  (String, Position) dco_decode_box_autoadd_record_string_position(dynamic raw);

  @protected
  Team dco_decode_box_autoadd_team(dynamic raw);

  @protected
  Difficulty dco_decode_difficulty(dynamic raw);

  @protected
  GameModeType dco_decode_game_mode_type(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<PieceView> dco_decode_list_piece_view(dynamic raw);

  @protected
  List<Position> dco_decode_list_position(dynamic raw);

  @protected
  List<PositionPath> dco_decode_list_position_path(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  BoardView? dco_decode_opt_box_autoadd_board_view(dynamic raw);

  @protected
  BotAction? dco_decode_opt_box_autoadd_bot_action(dynamic raw);

  @protected
  Position? dco_decode_opt_box_autoadd_position(dynamic raw);

  @protected
  (String, Position)? dco_decode_opt_box_autoadd_record_string_position(
    dynamic raw,
  );

  @protected
  Team? dco_decode_opt_box_autoadd_team(dynamic raw);

  @protected
  PieceRole dco_decode_piece_role(dynamic raw);

  @protected
  PieceView dco_decode_piece_view(dynamic raw);

  @protected
  Position dco_decode_position(dynamic raw);

  @protected
  PositionPath dco_decode_position_path(dynamic raw);

  @protected
  (String, Position) dco_decode_record_string_position(dynamic raw);

  @protected
  Team dco_decode_team(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  ActionResult sse_decode_action_result(SseDeserializer deserializer);

  @protected
  ActionType sse_decode_action_type(SseDeserializer deserializer);

  @protected
  BoardView sse_decode_board_view(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  BotAction sse_decode_bot_action(SseDeserializer deserializer);

  @protected
  BoardView sse_decode_box_autoadd_board_view(SseDeserializer deserializer);

  @protected
  BotAction sse_decode_box_autoadd_bot_action(SseDeserializer deserializer);

  @protected
  Position sse_decode_box_autoadd_position(SseDeserializer deserializer);

  @protected
  (String, Position) sse_decode_box_autoadd_record_string_position(
    SseDeserializer deserializer,
  );

  @protected
  Team sse_decode_box_autoadd_team(SseDeserializer deserializer);

  @protected
  Difficulty sse_decode_difficulty(SseDeserializer deserializer);

  @protected
  GameModeType sse_decode_game_mode_type(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<PieceView> sse_decode_list_piece_view(SseDeserializer deserializer);

  @protected
  List<Position> sse_decode_list_position(SseDeserializer deserializer);

  @protected
  List<PositionPath> sse_decode_list_position_path(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  BoardView? sse_decode_opt_box_autoadd_board_view(
    SseDeserializer deserializer,
  );

  @protected
  BotAction? sse_decode_opt_box_autoadd_bot_action(
    SseDeserializer deserializer,
  );

  @protected
  Position? sse_decode_opt_box_autoadd_position(SseDeserializer deserializer);

  @protected
  (String, Position)? sse_decode_opt_box_autoadd_record_string_position(
    SseDeserializer deserializer,
  );

  @protected
  Team? sse_decode_opt_box_autoadd_team(SseDeserializer deserializer);

  @protected
  PieceRole sse_decode_piece_role(SseDeserializer deserializer);

  @protected
  PieceView sse_decode_piece_view(SseDeserializer deserializer);

  @protected
  Position sse_decode_position(SseDeserializer deserializer);

  @protected
  PositionPath sse_decode_position_path(SseDeserializer deserializer);

  @protected
  (String, Position) sse_decode_record_string_position(
    SseDeserializer deserializer,
  );

  @protected
  Team sse_decode_team(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_list_prim_u_8_strict(utf8.encoder.convert(raw));
  }

  @protected
  ffi.Pointer<wire_cst_board_view> cst_encode_box_autoadd_board_view(
    BoardView raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_board_view();
    cst_api_fill_to_wire_board_view(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_cst_bot_action> cst_encode_box_autoadd_bot_action(
    BotAction raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_bot_action();
    cst_api_fill_to_wire_bot_action(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_cst_position> cst_encode_box_autoadd_position(Position raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_position();
    cst_api_fill_to_wire_position(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_cst_record_string_position>
  cst_encode_box_autoadd_record_string_position((String, Position) raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_record_string_position();
    cst_api_fill_to_wire_record_string_position(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<ffi.Int32> cst_encode_box_autoadd_team(Team raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return wire.cst_new_box_autoadd_team(cst_encode_team(raw));
  }

  @protected
  ffi.Pointer<wire_cst_list_piece_view> cst_encode_list_piece_view(
    List<PieceView> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_piece_view(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_piece_view(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_position> cst_encode_list_position(
    List<Position> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_position(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_position(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_position_path> cst_encode_list_position_path(
    List<PositionPath> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_position_path(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_position_path(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_list_prim_u_8_strict(
    Uint8List raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_u_8_strict(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_board_view> cst_encode_opt_box_autoadd_board_view(
    BoardView? raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_box_autoadd_board_view(raw);
  }

  @protected
  ffi.Pointer<wire_cst_bot_action> cst_encode_opt_box_autoadd_bot_action(
    BotAction? raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_box_autoadd_bot_action(raw);
  }

  @protected
  ffi.Pointer<wire_cst_position> cst_encode_opt_box_autoadd_position(
    Position? raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_box_autoadd_position(raw);
  }

  @protected
  ffi.Pointer<wire_cst_record_string_position>
  cst_encode_opt_box_autoadd_record_string_position((String, Position)? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null
        ? ffi.nullptr
        : cst_encode_box_autoadd_record_string_position(raw);
  }

  @protected
  ffi.Pointer<ffi.Int32> cst_encode_opt_box_autoadd_team(Team? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_box_autoadd_team(raw);
  }

  @protected
  void cst_api_fill_to_wire_action_result(
    ActionResult apiObj,
    wire_cst_action_result wireObj,
  ) {
    wireObj.success = cst_encode_bool(apiObj.success);
    wireObj.message = cst_encode_String(apiObj.message);
    wireObj.game_over = cst_encode_bool(apiObj.gameOver);
    wireObj.winner = cst_encode_opt_box_autoadd_team(apiObj.winner);
    wireObj.actions_remaining = cst_encode_u_8(apiObj.actionsRemaining);
  }

  @protected
  void cst_api_fill_to_wire_board_view(
    BoardView apiObj,
    wire_cst_board_view wireObj,
  ) {
    wireObj.pieces = cst_encode_list_piece_view(apiObj.pieces);
    wireObj.ball_position = cst_encode_opt_box_autoadd_position(
      apiObj.ballPosition,
    );
    wireObj.current_turn = cst_encode_team(apiObj.currentTurn);
    wireObj.actions_remaining = cst_encode_u_8(apiObj.actionsRemaining);
    wireObj.white_score = cst_encode_u_8(apiObj.whiteScore);
    wireObj.black_score = cst_encode_u_8(apiObj.blackScore);
    wireObj.turn_number = cst_encode_u_32(apiObj.turnNumber);
  }

  @protected
  void cst_api_fill_to_wire_bot_action(
    BotAction apiObj,
    wire_cst_bot_action wireObj,
  ) {
    wireObj.piece_id = cst_encode_String(apiObj.pieceId);
    wireObj.action_type = cst_encode_action_type(apiObj.actionType);
    wireObj.path = cst_encode_list_position(apiObj.path);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_board_view(
    BoardView apiObj,
    ffi.Pointer<wire_cst_board_view> wireObj,
  ) {
    cst_api_fill_to_wire_board_view(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_bot_action(
    BotAction apiObj,
    ffi.Pointer<wire_cst_bot_action> wireObj,
  ) {
    cst_api_fill_to_wire_bot_action(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_position(
    Position apiObj,
    ffi.Pointer<wire_cst_position> wireObj,
  ) {
    cst_api_fill_to_wire_position(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_record_string_position(
    (String, Position) apiObj,
    ffi.Pointer<wire_cst_record_string_position> wireObj,
  ) {
    cst_api_fill_to_wire_record_string_position(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_piece_view(
    PieceView apiObj,
    wire_cst_piece_view wireObj,
  ) {
    wireObj.id = cst_encode_String(apiObj.id);
    wireObj.team = cst_encode_team(apiObj.team);
    wireObj.role = cst_encode_piece_role(apiObj.role);
    cst_api_fill_to_wire_position(apiObj.position, wireObj.position);
    wireObj.has_ball = cst_encode_bool(apiObj.hasBall);
  }

  @protected
  void cst_api_fill_to_wire_position(
    Position apiObj,
    wire_cst_position wireObj,
  ) {
    wireObj.row = cst_encode_u_8(apiObj.row);
    wireObj.col = cst_encode_u_8(apiObj.col);
  }

  @protected
  void cst_api_fill_to_wire_position_path(
    PositionPath apiObj,
    wire_cst_position_path wireObj,
  ) {
    wireObj.positions = cst_encode_list_position(apiObj.positions);
  }

  @protected
  void cst_api_fill_to_wire_record_string_position(
    (String, Position) apiObj,
    wire_cst_record_string_position wireObj,
  ) {
    wireObj.field0 = cst_encode_String(apiObj.$1);
    cst_api_fill_to_wire_position(apiObj.$2, wireObj.field1);
  }

  @protected
  int cst_encode_action_type(ActionType raw);

  @protected
  bool cst_encode_bool(bool raw);

  @protected
  int cst_encode_difficulty(Difficulty raw);

  @protected
  int cst_encode_game_mode_type(GameModeType raw);

  @protected
  int cst_encode_i_32(int raw);

  @protected
  int cst_encode_piece_role(PieceRole raw);

  @protected
  int cst_encode_team(Team raw);

  @protected
  int cst_encode_u_32(int raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_action_result(ActionResult self, SseSerializer serializer);

  @protected
  void sse_encode_action_type(ActionType self, SseSerializer serializer);

  @protected
  void sse_encode_board_view(BoardView self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_bot_action(BotAction self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_board_view(
    BoardView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bot_action(
    BotAction self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_position(Position self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_record_string_position(
    (String, Position) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_team(Team self, SseSerializer serializer);

  @protected
  void sse_encode_difficulty(Difficulty self, SseSerializer serializer);

  @protected
  void sse_encode_game_mode_type(GameModeType self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_piece_view(
    List<PieceView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_position(List<Position> self, SseSerializer serializer);

  @protected
  void sse_encode_list_position_path(
    List<PositionPath> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_board_view(
    BoardView? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_bot_action(
    BotAction? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_position(
    Position? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_record_string_position(
    (String, Position)? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_team(Team? self, SseSerializer serializer);

  @protected
  void sse_encode_piece_role(PieceRole self, SseSerializer serializer);

  @protected
  void sse_encode_piece_view(PieceView self, SseSerializer serializer);

  @protected
  void sse_encode_position(Position self, SseSerializer serializer);

  @protected
  void sse_encode_position_path(PositionPath self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_position(
    (String, Position) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_team(Team self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

// ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint

/// generated by flutter_rust_bridge
class XfutebolBridgeWire implements BaseWire {
  factory XfutebolBridgeWire.fromExternalLibrary(ExternalLibrary lib) =>
      XfutebolBridgeWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  XfutebolBridgeWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  XfutebolBridgeWire.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  void store_dart_post_cobject(DartPostCObjectFnType ptr) {
    return _store_dart_post_cobject(ptr);
  }

  late final _store_dart_post_cobjectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(DartPostCObjectFnType)>>(
        'store_dart_post_cobject',
      );
  late final _store_dart_post_cobject = _store_dart_post_cobjectPtr
      .asFunction<void Function(DartPostCObjectFnType)>();

  void wire__crate__api__delete_game(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> game_id,
  ) {
    return _wire__crate__api__delete_game(port_, game_id);
  }

  late final _wire__crate__api__delete_gamePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_xfutebol_flutter_bridge_wire__crate__api__delete_game');
  late final _wire__crate__api__delete_game = _wire__crate__api__delete_gamePtr
      .asFunction<
        void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
      >();

  void wire__crate__api__execute_defend(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> game_id,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> piece_id,
    ffi.Pointer<wire_cst_list_position> path,
  ) {
    return _wire__crate__api__execute_defend(port_, game_id, piece_id, path);
  }

  late final _wire__crate__api__execute_defendPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_position>,
          )
        >
      >('frbgen_xfutebol_flutter_bridge_wire__crate__api__execute_defend');
  late final _wire__crate__api__execute_defend =
      _wire__crate__api__execute_defendPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_position>,
            )
          >();

  void wire__crate__api__execute_intercept(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> game_id,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> piece_id,
    ffi.Pointer<wire_cst_list_position> path,
  ) {
    return _wire__crate__api__execute_intercept(port_, game_id, piece_id, path);
  }

  late final _wire__crate__api__execute_interceptPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_position>,
          )
        >
      >('frbgen_xfutebol_flutter_bridge_wire__crate__api__execute_intercept');
  late final _wire__crate__api__execute_intercept =
      _wire__crate__api__execute_interceptPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_position>,
            )
          >();

  void wire__crate__api__execute_kick(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> game_id,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> piece_id,
    ffi.Pointer<wire_cst_list_position> path,
  ) {
    return _wire__crate__api__execute_kick(port_, game_id, piece_id, path);
  }

  late final _wire__crate__api__execute_kickPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_position>,
          )
        >
      >('frbgen_xfutebol_flutter_bridge_wire__crate__api__execute_kick');
  late final _wire__crate__api__execute_kick =
      _wire__crate__api__execute_kickPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_position>,
            )
          >();

  void wire__crate__api__execute_move(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> game_id,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> piece_id,
    ffi.Pointer<wire_cst_position> to,
  ) {
    return _wire__crate__api__execute_move(port_, game_id, piece_id, to);
  }

  late final _wire__crate__api__execute_movePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_position>,
          )
        >
      >('frbgen_xfutebol_flutter_bridge_wire__crate__api__execute_move');
  late final _wire__crate__api__execute_move =
      _wire__crate__api__execute_movePtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_position>,
            )
          >();

  void wire__crate__api__execute_pass(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> game_id,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> piece_id,
    ffi.Pointer<wire_cst_list_position> path,
  ) {
    return _wire__crate__api__execute_pass(port_, game_id, piece_id, path);
  }

  late final _wire__crate__api__execute_passPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_position>,
          )
        >
      >('frbgen_xfutebol_flutter_bridge_wire__crate__api__execute_pass');
  late final _wire__crate__api__execute_pass =
      _wire__crate__api__execute_passPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_position>,
            )
          >();

  void wire__crate__api__execute_push(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> game_id,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> piece_id,
    ffi.Pointer<wire_cst_position> target,
    ffi.Pointer<wire_cst_position> destination,
  ) {
    return _wire__crate__api__execute_push(
      port_,
      game_id,
      piece_id,
      target,
      destination,
    );
  }

  late final _wire__crate__api__execute_pushPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_position>,
            ffi.Pointer<wire_cst_position>,
          )
        >
      >('frbgen_xfutebol_flutter_bridge_wire__crate__api__execute_push');
  late final _wire__crate__api__execute_push =
      _wire__crate__api__execute_pushPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_position>,
              ffi.Pointer<wire_cst_position>,
            )
          >();

  void wire__crate__api__execute_shoot(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> game_id,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> piece_id,
    ffi.Pointer<wire_cst_list_position> path,
  ) {
    return _wire__crate__api__execute_shoot(port_, game_id, piece_id, path);
  }

  late final _wire__crate__api__execute_shootPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_position>,
          )
        >
      >('frbgen_xfutebol_flutter_bridge_wire__crate__api__execute_shoot');
  late final _wire__crate__api__execute_shoot =
      _wire__crate__api__execute_shootPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_position>,
            )
          >();

  void wire__crate__api__game_exists(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> game_id,
  ) {
    return _wire__crate__api__game_exists(port_, game_id);
  }

  late final _wire__crate__api__game_existsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_xfutebol_flutter_bridge_wire__crate__api__game_exists');
  late final _wire__crate__api__game_exists = _wire__crate__api__game_existsPtr
      .asFunction<
        void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
      >();

  void wire__crate__api__get_board(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> game_id,
  ) {
    return _wire__crate__api__get_board(port_, game_id);
  }

  late final _wire__crate__api__get_boardPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_xfutebol_flutter_bridge_wire__crate__api__get_board');
  late final _wire__crate__api__get_board = _wire__crate__api__get_boardPtr
      .asFunction<
        void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
      >();

  void wire__crate__api__get_bot_action(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> game_id,
    int difficulty,
  ) {
    return _wire__crate__api__get_bot_action(port_, game_id, difficulty);
  }

  late final _wire__crate__api__get_bot_actionPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Int32,
          )
        >
      >('frbgen_xfutebol_flutter_bridge_wire__crate__api__get_bot_action');
  late final _wire__crate__api__get_bot_action =
      _wire__crate__api__get_bot_actionPtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>, int)
          >();

  void wire__crate__api__get_bot_move(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> game_id,
    int difficulty,
  ) {
    return _wire__crate__api__get_bot_move(port_, game_id, difficulty);
  }

  late final _wire__crate__api__get_bot_movePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Int32,
          )
        >
      >('frbgen_xfutebol_flutter_bridge_wire__crate__api__get_bot_move');
  late final _wire__crate__api__get_bot_move =
      _wire__crate__api__get_bot_movePtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>, int)
          >();

  void wire__crate__api__get_legal_defends(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> game_id,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> piece_id,
  ) {
    return _wire__crate__api__get_legal_defends(port_, game_id, piece_id);
  }

  late final _wire__crate__api__get_legal_defendsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_xfutebol_flutter_bridge_wire__crate__api__get_legal_defends');
  late final _wire__crate__api__get_legal_defends =
      _wire__crate__api__get_legal_defendsPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__get_legal_intercepts(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> game_id,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> piece_id,
  ) {
    return _wire__crate__api__get_legal_intercepts(port_, game_id, piece_id);
  }

  late final _wire__crate__api__get_legal_interceptsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >(
        'frbgen_xfutebol_flutter_bridge_wire__crate__api__get_legal_intercepts',
      );
  late final _wire__crate__api__get_legal_intercepts =
      _wire__crate__api__get_legal_interceptsPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__get_legal_kicks(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> game_id,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> piece_id,
  ) {
    return _wire__crate__api__get_legal_kicks(port_, game_id, piece_id);
  }

  late final _wire__crate__api__get_legal_kicksPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_xfutebol_flutter_bridge_wire__crate__api__get_legal_kicks');
  late final _wire__crate__api__get_legal_kicks =
      _wire__crate__api__get_legal_kicksPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__get_legal_moves(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> game_id,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> piece_id,
  ) {
    return _wire__crate__api__get_legal_moves(port_, game_id, piece_id);
  }

  late final _wire__crate__api__get_legal_movesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_xfutebol_flutter_bridge_wire__crate__api__get_legal_moves');
  late final _wire__crate__api__get_legal_moves =
      _wire__crate__api__get_legal_movesPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__get_legal_passes(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> game_id,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> piece_id,
  ) {
    return _wire__crate__api__get_legal_passes(port_, game_id, piece_id);
  }

  late final _wire__crate__api__get_legal_passesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_xfutebol_flutter_bridge_wire__crate__api__get_legal_passes');
  late final _wire__crate__api__get_legal_passes =
      _wire__crate__api__get_legal_passesPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__get_legal_pushes(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> game_id,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> piece_id,
  ) {
    return _wire__crate__api__get_legal_pushes(port_, game_id, piece_id);
  }

  late final _wire__crate__api__get_legal_pushesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_xfutebol_flutter_bridge_wire__crate__api__get_legal_pushes');
  late final _wire__crate__api__get_legal_pushes =
      _wire__crate__api__get_legal_pushesPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__get_legal_shoots(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> game_id,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> piece_id,
  ) {
    return _wire__crate__api__get_legal_shoots(port_, game_id, piece_id);
  }

  late final _wire__crate__api__get_legal_shootsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_xfutebol_flutter_bridge_wire__crate__api__get_legal_shoots');
  late final _wire__crate__api__get_legal_shoots =
      _wire__crate__api__get_legal_shootsPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__get_winner(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> game_id,
  ) {
    return _wire__crate__api__get_winner(port_, game_id);
  }

  late final _wire__crate__api__get_winnerPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_xfutebol_flutter_bridge_wire__crate__api__get_winner');
  late final _wire__crate__api__get_winner = _wire__crate__api__get_winnerPtr
      .asFunction<
        void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
      >();

  void wire__crate__api__greet(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> name,
  ) {
    return _wire__crate__api__greet(port_, name);
  }

  late final _wire__crate__api__greetPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_xfutebol_flutter_bridge_wire__crate__api__greet');
  late final _wire__crate__api__greet = _wire__crate__api__greetPtr
      .asFunction<
        void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
      >();

  void wire__crate__api__is_game_over(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> game_id,
  ) {
    return _wire__crate__api__is_game_over(port_, game_id);
  }

  late final _wire__crate__api__is_game_overPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_xfutebol_flutter_bridge_wire__crate__api__is_game_over');
  late final _wire__crate__api__is_game_over =
      _wire__crate__api__is_game_overPtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
          >();

  void wire__crate__api__new_game(int port_, int mode) {
    return _wire__crate__api__new_game(port_, mode);
  }

  late final _wire__crate__api__new_gamePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Int32)>>(
        'frbgen_xfutebol_flutter_bridge_wire__crate__api__new_game',
      );
  late final _wire__crate__api__new_game = _wire__crate__api__new_gamePtr
      .asFunction<void Function(int, int)>();

  ffi.Pointer<wire_cst_board_view> cst_new_box_autoadd_board_view() {
    return _cst_new_box_autoadd_board_view();
  }

  late final _cst_new_box_autoadd_board_viewPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_cst_board_view> Function()>>(
        'frbgen_xfutebol_flutter_bridge_cst_new_box_autoadd_board_view',
      );
  late final _cst_new_box_autoadd_board_view =
      _cst_new_box_autoadd_board_viewPtr
          .asFunction<ffi.Pointer<wire_cst_board_view> Function()>();

  ffi.Pointer<wire_cst_bot_action> cst_new_box_autoadd_bot_action() {
    return _cst_new_box_autoadd_bot_action();
  }

  late final _cst_new_box_autoadd_bot_actionPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_cst_bot_action> Function()>>(
        'frbgen_xfutebol_flutter_bridge_cst_new_box_autoadd_bot_action',
      );
  late final _cst_new_box_autoadd_bot_action =
      _cst_new_box_autoadd_bot_actionPtr
          .asFunction<ffi.Pointer<wire_cst_bot_action> Function()>();

  ffi.Pointer<wire_cst_position> cst_new_box_autoadd_position() {
    return _cst_new_box_autoadd_position();
  }

  late final _cst_new_box_autoadd_positionPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_cst_position> Function()>>(
        'frbgen_xfutebol_flutter_bridge_cst_new_box_autoadd_position',
      );
  late final _cst_new_box_autoadd_position = _cst_new_box_autoadd_positionPtr
      .asFunction<ffi.Pointer<wire_cst_position> Function()>();

  ffi.Pointer<wire_cst_record_string_position>
  cst_new_box_autoadd_record_string_position() {
    return _cst_new_box_autoadd_record_string_position();
  }

  late final _cst_new_box_autoadd_record_string_positionPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_record_string_position> Function()
        >
      >(
        'frbgen_xfutebol_flutter_bridge_cst_new_box_autoadd_record_string_position',
      );
  late final _cst_new_box_autoadd_record_string_position =
      _cst_new_box_autoadd_record_string_positionPtr
          .asFunction<
            ffi.Pointer<wire_cst_record_string_position> Function()
          >();

  ffi.Pointer<ffi.Int32> cst_new_box_autoadd_team(int value) {
    return _cst_new_box_autoadd_team(value);
  }

  late final _cst_new_box_autoadd_teamPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Int32> Function(ffi.Int32)>>(
        'frbgen_xfutebol_flutter_bridge_cst_new_box_autoadd_team',
      );
  late final _cst_new_box_autoadd_team = _cst_new_box_autoadd_teamPtr
      .asFunction<ffi.Pointer<ffi.Int32> Function(int)>();

  ffi.Pointer<wire_cst_list_piece_view> cst_new_list_piece_view(int len) {
    return _cst_new_list_piece_view(len);
  }

  late final _cst_new_list_piece_viewPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_piece_view> Function(ffi.Int32)
        >
      >('frbgen_xfutebol_flutter_bridge_cst_new_list_piece_view');
  late final _cst_new_list_piece_view = _cst_new_list_piece_viewPtr
      .asFunction<ffi.Pointer<wire_cst_list_piece_view> Function(int)>();

  ffi.Pointer<wire_cst_list_position> cst_new_list_position(int len) {
    return _cst_new_list_position(len);
  }

  late final _cst_new_list_positionPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_position> Function(ffi.Int32)
        >
      >('frbgen_xfutebol_flutter_bridge_cst_new_list_position');
  late final _cst_new_list_position = _cst_new_list_positionPtr
      .asFunction<ffi.Pointer<wire_cst_list_position> Function(int)>();

  ffi.Pointer<wire_cst_list_position_path> cst_new_list_position_path(int len) {
    return _cst_new_list_position_path(len);
  }

  late final _cst_new_list_position_pathPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_position_path> Function(ffi.Int32)
        >
      >('frbgen_xfutebol_flutter_bridge_cst_new_list_position_path');
  late final _cst_new_list_position_path = _cst_new_list_position_pathPtr
      .asFunction<ffi.Pointer<wire_cst_list_position_path> Function(int)>();

  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_new_list_prim_u_8_strict(
    int len,
  ) {
    return _cst_new_list_prim_u_8_strict(len);
  }

  late final _cst_new_list_prim_u_8_strictPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(ffi.Int32)
        >
      >('frbgen_xfutebol_flutter_bridge_cst_new_list_prim_u_8_strict');
  late final _cst_new_list_prim_u_8_strict = _cst_new_list_prim_u_8_strictPtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(int)>();

  int dummy_method_to_enforce_bundling() {
    return _dummy_method_to_enforce_bundling();
  }

  late final _dummy_method_to_enforce_bundlingPtr =
      _lookup<ffi.NativeFunction<ffi.Int64 Function()>>(
        'dummy_method_to_enforce_bundling',
      );
  late final _dummy_method_to_enforce_bundling =
      _dummy_method_to_enforce_bundlingPtr.asFunction<int Function()>();
}

typedef DartPostCObjectFnType =
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Bool Function(DartPort port_id, ffi.Pointer<ffi.Void> message)
      >
    >;
typedef DartPort = ffi.Int64;

final class wire_cst_list_prim_u_8_strict extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_position extends ffi.Struct {
  @ffi.Uint8()
  external int row;

  @ffi.Uint8()
  external int col;
}

final class wire_cst_list_position extends ffi.Struct {
  external ffi.Pointer<wire_cst_position> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_piece_view extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> id;

  @ffi.Int32()
  external int team;

  @ffi.Int32()
  external int role;

  external wire_cst_position position;

  @ffi.Bool()
  external bool has_ball;
}

final class wire_cst_list_piece_view extends ffi.Struct {
  external ffi.Pointer<wire_cst_piece_view> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_board_view extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_piece_view> pieces;

  external ffi.Pointer<wire_cst_position> ball_position;

  @ffi.Int32()
  external int current_turn;

  @ffi.Uint8()
  external int actions_remaining;

  @ffi.Uint8()
  external int white_score;

  @ffi.Uint8()
  external int black_score;

  @ffi.Uint32()
  external int turn_number;
}

final class wire_cst_bot_action extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> piece_id;

  @ffi.Int32()
  external int action_type;

  external ffi.Pointer<wire_cst_list_position> path;
}

final class wire_cst_record_string_position extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> field0;

  external wire_cst_position field1;
}

final class wire_cst_position_path extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_position> positions;
}

final class wire_cst_list_position_path extends ffi.Struct {
  external ffi.Pointer<wire_cst_position_path> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_action_result extends ffi.Struct {
  @ffi.Bool()
  external bool success;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> message;

  @ffi.Bool()
  external bool game_over;

  external ffi.Pointer<ffi.Int32> winner;

  @ffi.Uint8()
  external int actions_remaining;
}
